# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3.8'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'POSTGRESQL_DATABASE=bizonev2'
volumes:
  postgresql_data:
    driver: local
